"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.DEFAULT_WIDTH = exports.DEFAULT_TEXT_SIZE = exports.DEFAULT_TEXT_COLOR = exports.DEFAULT_RELEASE_DELAY = exports.DEFAULT_RAISE_LEVEL = exports.DEFAULT_LINE_HEIGHT = exports.DEFAULT_HORIZONTAL_PADDING = exports.DEFAULT_HEIGHT = exports.DEFAULT_DEBOUNCED_PRESS_TIME = exports.DEFAULT_BORDER_WIDTH = exports.DEFAULT_BORDER_RADIUS = exports.DEFAULT_BACKGROUND_SHADOW = exports.DEFAULT_BACKGROUND_DARKER = exports.DEFAULT_BACKGROUND_COLOR = exports.DEFAULT_BACKGROUND_ACTIVE = exports.DEFAULT_ACTIVITY_COLOR = exports.DEFAULT_ACTIVE_OPACITY = exports.ANIMATED_TIMING_OFF = exports.ANIMATED_TIMING_LOADING = exports.ANIMATED_TIMING_IN = exports.ANIMATED_SPRING_TENSION = exports.ANIMATED_SPRING_FRICTION = exports.ANIMATED_ELASTIC_DURATION = exports.ANIMATED_ELASTIC_BOUNCINESS = void 0;
const ANIMATED_SPRING_FRICTION = exports.ANIMATED_SPRING_FRICTION = 6.75;
const ANIMATED_SPRING_TENSION = exports.ANIMATED_SPRING_TENSION = 100;
const ANIMATED_ELASTIC_DURATION = exports.ANIMATED_ELASTIC_DURATION = 300;
const ANIMATED_ELASTIC_BOUNCINESS = exports.ANIMATED_ELASTIC_BOUNCINESS = 1.2;
const ANIMATED_TIMING_OFF = exports.ANIMATED_TIMING_OFF = 100;
const ANIMATED_TIMING_IN = exports.ANIMATED_TIMING_IN = 200;
const ANIMATED_TIMING_LOADING = exports.ANIMATED_TIMING_LOADING = 3000;
const DEFAULT_RAISE_LEVEL = exports.DEFAULT_RAISE_LEVEL = 4;
const DEFAULT_ACTIVE_OPACITY = exports.DEFAULT_ACTIVE_OPACITY = 1;
const DEFAULT_RELEASE_DELAY = exports.DEFAULT_RELEASE_DELAY = 100;
const DEFAULT_HEIGHT = exports.DEFAULT_HEIGHT = 60;
const DEFAULT_WIDTH = exports.DEFAULT_WIDTH = null;
const DEFAULT_DEBOUNCED_PRESS_TIME = exports.DEFAULT_DEBOUNCED_PRESS_TIME = 0;
const DEFAULT_BORDER_RADIUS = exports.DEFAULT_BORDER_RADIUS = 4;
const DEFAULT_BORDER_WIDTH = exports.DEFAULT_BORDER_WIDTH = 0;
const DEFAULT_HORIZONTAL_PADDING = exports.DEFAULT_HORIZONTAL_PADDING = 16;
const DEFAULT_TEXT_COLOR = exports.DEFAULT_TEXT_COLOR = '#FFFFFF';
const DEFAULT_ACTIVITY_COLOR = exports.DEFAULT_ACTIVITY_COLOR = '#FFFFFF';
const DEFAULT_BACKGROUND_COLOR = exports.DEFAULT_BACKGROUND_COLOR = '#c0c0c0';
const DEFAULT_BACKGROUND_DARKER = exports.DEFAULT_BACKGROUND_DARKER = '#9f9f9f';
const DEFAULT_BACKGROUND_SHADOW = exports.DEFAULT_BACKGROUND_SHADOW = 'rgba(0, 0, 0, 0.15)';
const DEFAULT_BACKGROUND_ACTIVE = exports.DEFAULT_BACKGROUND_ACTIVE = 'rgba(0, 0, 0, 0.15)';
const DEFAULT_LINE_HEIGHT = exports.DEFAULT_LINE_HEIGHT = 20;
const DEFAULT_TEXT_SIZE = exports.DEFAULT_TEXT_SIZE = 14;
//# sourceMappingURL=constants.js.map